name: Build APK

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDebug
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk 
      
    - name: Commit APK
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'battlecatsupload+github-actions[bot]@users.noreply.github.com'
        git add app/build/outputs/apk/debug/app-debug.apk
        git commit -m "Upload APK"
        git push
